language: python
python: '3.6'
dist: trusty
sudo: true
services:
- postgresql
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
  - DATABASE_URL="postgres://postgres:@localhost/travis_ci_test"
  - ENVIRONMENT="TEST"
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: fLt0co4W7XxUV75DfAE+74UDBzreUEdoteExd4xG2l7ccROmLdlMQreXvxOLqvxOe2AKSlnYc0ULjQQrCC5I+k1jOhdk6/zm6+8OZULulM3Vxneffaa8P7N+JgkxWtIqLdqP3xu+SanRKpnM31m69blz3e10+qSV7tSh140zJ4Nw/K/XMbCUiS8uwddVsJpO1gO77usyCwouHIogD9sDhrWoqUpDajtT4BuahK2WHxfeeBAcRElFVMf1aUihuraeg0u4QaffbvAfo7qVp9PhZg4Mtem/S9RkgdYsPMRaUijCIh8fmoO7nLxiJB28C9HS8qfOt+GXx9XOFhN7thUfKDe9PDnZbzv0FgOE5Y1F1z3qDa26M0mO6/G7vc5vwTdf8TiukBdeTliIjk++pKQoh5Y6MKVibWPIvo+fJ26tO8Aj5Zq0YDHFiHoFnL9k/QotXv27xsustMEdMWvZgKrv+efjUc3JCsWHo3cjqbLvt6gj7q2JO5TSpKDcQKUpT2OgavyEGLxQqvwwsYWkuP6rXQ102EMaPyuD8Jn/apDSrPoHY9Nbr/V0BrZfFaFRIgYURhmoCn5lBJETLiaYN1EV+yDrkJVu6OyvOyGJNwjbM07YbDRXTBklzzQwyxt15DXdR2s4sJUUAPd/uvbuMd5c63LNUBjlUqzmW9T7y9sEpzE=
  app: reviewer-api
  on:
    repo: murilocamargos/reviewer-api
  run: python manage.py migrate
