language: python
python: '3.6'
dist: trusty
sudo: true
services:
- postgresql
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
  - DATABASE_URL="postgres://postgres:@localhost/travis_ci_test"
  - ENVIRONMENT="TEST"
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: L7cYOGMywOblm/K54TQc1l4sUk5UG+/SzG8KilOQuScVjDZ/99XndxB6XXNqdJZtF3/nq4eEW4VZsROTRMYSsQW5AQZ3fm/wNRptj
  app: reviewer-api
  on:
    repo: murilocamargos/reviewer-api
  run: python manage.py migrate