language: python
python: '3.6'
dist: trusty
sudo: true
services:
- postgresql
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
  - DATABASE_URL="postgres://postgres:@localhost/travis_ci_test"
  - ENVIRONMENT="TEST"
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: "mlm4K3TT25nLaiO0QKDzNIxHRg8jhA6fZoGYWsc1OhRXDnHfzAyvKGWFUpmTBj3n6Lxb3ZXVDx0PRrq1TUTa6vCwQysjK5FkkW7S9vYX6fiR4baPRNREfFxi1iiD3/BwVjLJIm4mnl8DqKQ+UNnLlzOBdoB69sAO/F//6qjs7BTFoeRASd2DQCarPww9rBY3IVjvOek3fAd5aIveuiTn1KD3ktR/LfuszpYJNXd4rgj7EC6uNuVqEyH7ACVr7UG8XIl5FqJcVWYzn/hU1G8tpjgal4WUZEQN1nguhGpNKp4TuT94Tu7dbNFUICG7GjOU6fY6XG3qW2qIO9ktNrGIPGtWG3BjOqwuAnKr455iYlxoJ3BChUDGV+Sw6fuG05Y3NFS39F7Gh8OzaRf7XcGQILwawJUd9vRUjCKTT94OkiA8ujCeRG7fZVibqDpl2jiMEH+51caRCgNVF24Vwf/yYVBqo62VE9myy5JAL5dNfW7vKX6Y8UuOktFdAaBkvvCjJSGbcgO+6kJ08WvG2hnTeBETG9kPBXtY0xKg/YSSyGJzxHfTw7oedIWvyGd2WnJUHRcglonN8L5cAj8mluO++YM6cOaVFGi/0JlSErFDtEIYGVQoageGQN4PDME75WvUUj/7HHx8nUXBWsnHVWC20JM/Y97d2ibQLL/YpchWgBY="
  app: reviewer-api
  on:
    repo: murilocamargos/reviewer-api
  run: python manage.py migrate
