language: python
python: '3.6'
dist: trusty
sudo: true
services:
- postgresql
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
  - DATABASE_URL="postgres://postgres:@localhost/travis_ci_test"
  - ENVIRONMENT="TEST"
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: LA5SRzhZy9+bOtBaXAhljeDrThzBHESmowqiGiZckVDPQf/JvenKGm2DQPVHuJZq0qq2qPV4q7yie5RDR+Cp9NOyYvolQ/i+8RugVQ4E2aqOUD5Xf3PwK92Y0AoqRVIE5oYvToXk+A+ozetiI2EXcB+AxTfUhw4Mur1bxcYS6LT3y1s9M9CwNyxPUglhzhkzO54ETmKaUZeUOoSRJ433bLag/RFJXUEu/l0rO4okM3R8bVmvzrmbxngqZi+SEBPrpqGlRs15R6aCLDy34a1gvTjz/IymPS1glsHRLkHN1f2fLTqehipfaJqQurPUMxrwDil4c44w5EX6fMDFAk5nh3OA3qSAW82ASGpKYUomwB60U50vcYPnkczShjZ25bGj2x9ZPVnHv1YJWwRORhOh3gpTbdH6WYIOw6v3WVX0MUR9nG1LxCkhCgu+GyXmSJAbO1YVY788CbdXFX/gQXqOY627ZO0Mg30bGzw5nZf1a9axeaaRVm2TZm5r9fNM/yB7LLGhaM7rkLT5WLLIG7rM2fIeg4j4gNn1utF4NijcGGHgwcTuvI0yCvTXeb7o5N6dcbWlteVjLcWAowyzsqIv+AMnN0AtX2cu7+iWtRQ/E/gvTs/z2ToeZs7/mH0i4jUy6DA/1h8Xs6T4LL/tY9Ni9w/JRT+3VxXUmiKA37uW7Ag=
  app: reviewer-api
  on: master
  run: python manage.py migrate
