language: python
python: '3.6'
dist: trusty
sudo: true
services:
- postgresql
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
  - DATABASE_URL="postgres://postgres:@localhost/travis_ci_test"
  - ENVIRONMENT="TEST"
  - secure: Ph9pprIPeJ9JLQjVmnegarKlI75+jCBXQDt2qsnaxgunzluCpBzW3beHqHcwGLkDuDQ9z2ELx3DnXMqq/X0iIhYZH8SoiYVfLf2YawUj/cIEblCpIMPvEmP5uTKQLztiLK7/OrtOHnjfwm/RLLpv8WvckwiC2T/NBOqRmq1YPcU1PAho+mF8RHcN4Wjl3g5MppJHuQKyt+mTDl18qOnhcz++UoFZtOaG5ZXSmwRPfPiUEa6lySNvxwg59o6laBhuRpYmXlgykFKVFs79iOoMSlhRGZ4wn6Gzu6PuVa3HYmmsa3MrC+jks73zx8gjqE6obKPOqziKiKEHUurCn+xEmUft6MoAIW7+8SIWktw8+dJvNbI2MU5g5upwGNf6zreZkJfXyuumXDLYCVY73GcqznKS9mmyDx+NHQ6NneuURIto+9GQSg5jP1ztqXiZSOtzrxAlFzX4DvoZR7+d9GE1tY/aJl9RdRd4/RMcSWYedAiAuuLPpUnFuhHUoOyUaBLmKYqBV2g67RF5fG5JvJ7sAgNAyQ/ObvkfGerHeTtKH3DbxhmayzqaNDnuh3IZoN8+WGvAnULatFFPUL70Y7Cds7IBPDGM1Zg1vgTIQ2Plc8AD4XJLrhc58QHZEBSIhrhHEKqHUOr8JFLEwx4+6I6jyEksMBUDavCKj4e6Dm+VZC0=
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: j+Megq+eORUlHmgUxocpjsHJRKKkz4cnsSc/MyB0jWl30FDthEOspiDhVPFA5TCqN8jLPXEb4bNNDMQGicP6UZUaUR8KsO99TNrqcRnjid8kq7r2950+ss3gDaZdz2NxbXOBi+xJLj24ziHD72oHGcef221z5jeJIW5JLy4Da6IW7pQ4nS4Zi7GcYVVmo27uSMEEqzzj0jPfwWN6Bm98nmZqvR1R5ibT79LgaGe/S8YPuuIlrjl8GwMScUWdno/TmOqskB42srWACuRL9p7CN8EFjvPB++uIO9Pfj1SjGanbxSRjjNmVgf3z9d0DNMZfl2pk0U3o7+erU5+vEZ7byQPmObFOu2IuUT9Hhc9cVux/eQNJXrkNBfg1JRtrNpmtQMwbFwHvhqn4kBXhvZ/InImJlFvezfgs0RplDFmMhMN7ckjaOpx3yu2NFchSwTzDtGpeMI/BKqeRy4bc6E3MstS2a7tvc/R6Jp4QMQ3DelG5rGKnSlQ0KnW4uQfcPwD6u8RbDWCLXpDU/2xIYoBD1L+uM0AvSNgmEM79uVFS/zm+VczJQoASIrwnN3ZPufZs6/lCqTTpp0Jfef0fuGlh7lAUwcOZVgytXkrA+fiKolLezIPTIMI0cSrmBsxgPQmTg/A/YbqgfwGYqTHUyI/wlogVTxwk5UzLVrtrZUCA0ag=
  app: reviewer-api
  on: master
  run: python manage.py migrate
