language: python
python: '3.6'
dist: trusty
sudo: true
services:
- postgresql
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
  - DATABASE_URL="postgres://postgres:@localhost/travis_ci_test"
  - ENVIRONMENT="TEST"
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: lroI027vv9S58St22aUi5dFQ8g5DTPn6q0xd9G2gpeD+bRfP+kJ0CzuFb6sfLHY+3QJ9R63UDGZf8cAFeej7NerDVnyTm6zRrSDN4zgBr01TbyQHkDu43iWgNHacNIFxoK92K9wGYGi+prmN0Tn+qXu0RD2YbeyUHUDYGJqzMCqoLcdEOhQ8Tg2AZzq3nQPEG0/QnWygCXn9oGIMsayXgHjNzM+X+GXrzDSgU2Ns2Q4n78d3VkSP+d4amv+gY1bYn+fl6xx9PTb/FuHhWNSWXIYDHal+2osZrSHn56l9tBKRBb5hDl3chOXDI+iQYUZPOr3YTpiv8I+friU3a0JfIh9mPoqgh9Dc03CZ80GcxBmobRSCKky43VFks6odPrM/K6hKiJtS2FLoXw//qlvWR28AjNUw8uOyk7fKzxqalpEsauWUtJMGcnYfql23Nnetj1eWgtrROezV3RY0yCv8IhnPzRgbYLjt3g/iBhba1BmMdEue+G1pU0wV1uK8nExVXizXgk20Ztt5lNCpbjqb3xUgsnACwJ3lipLxvm15VGBgQDUGzkIJXKkkTdo5u5ea9VdVfmnBS6nk1wmAWYfR8Bkct83f3L/o8MNQuNhX+Eq+eszrWMg2AVvD/xNFXdPhmsE3oo9mnip8zUGFblD1VZ1S9Q11eAFnHfnDbpeQJT8=
  app: reviewer-api
  on: master
  run: python manage.py migrate
