language: python
python: '3.6'
dist: trusty
sudo: true
services:
- postgresql
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
  - DATABASE_URL="postgres://postgres:@localhost/travis_ci_test"
  - ENVIRONMENT="TEST"
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: pEre9GVgYbMU1ZPAXiD+kUWy+nDxGyYTSJbVZwV33VNMRLKoGT6eGY/KJdT7fWvbgxG1/HaSZJhzrDgCn80xk//EFL2pwxNJnsmcQqbT/HmhoGbk3tCosfevigB+o7muOnUjMpUhHMV6f7RVB5d6kWY2dqI6665MrRVN/i1F6KMWCE8RHLbCUiZqRmYwp4/a29VE9TeQZFHO1NtPMsQXpVij2L/VCdp1N5ad7lWwQ5zuynHEKbpEDoxkTg/85mrm49el7okatHXGCIcggBsqTXjz09/DX6auwkM+m28nnCJgi138DxYbnTf2+sgMqOiX7XGl990HFUbSN84Aik6tA5nljS4GG19a9aKOokoCMB0+GSSNBefpC7vk/XdruCrEdlUMT3lc+uoRPUmNzSmh0t641TabNclr/kPpGoa+MP3ibFuOn072NUK1kNAfP8n/vbKqQB0pE2ZFWFKEMPslGkSnHZuCRf8TuEd2imcTzVfvVQSRxWqf+ZlkrkhI0c2/qBo0QelPpKF8TLFdjEL4sr8u3fI+I+sXcTEGeFTE+Ki6G0RTIE519ANOylHRRr1qRXF162Dh9byOVPd+0mDtKur6l1uQdOeWwEUoiA0JBhiX/sdJjNykTKkv4lzAx2YSJ1QCghxA2NH07FSWES5n+HPDr+KId/Yn0iN3E8LOML0=
  app: api-reviewer
  on:
    repo: murilocamargos/reviewer-api
  run: python manage.py migrate