language: python
python: '3.6'
dist: trusty
sudo: true
services:
- postgresql
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
  - DATABASE_URL="postgres://postgres:@localhost/travis_ci_test"
  - ENVIRONMENT="TEST"
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: HPqgYGgmNi5w1YVVTwsOlOEenUdWdRkewYxIJjD9LMLjIaZnZ53JMytnTtQuQB+bKpMv5PppVdHl+PUuM64RSXIK3+eXbunGKDcVrofYhh/SgidjtBKtwPhwBvBcONjPCnzNMPpxGe98O8kdUSnE3xQq7iw91bKS1oBk/9dVQKvI/sORw1nbzRWSf3dj+VG+1I1krshMhTGQ2IFT2FBtxlsbng4hbFAGmA4D7NWapsiKT/xDKx/dZ+FykrCfvjiC42xlPSWljkSdktw/CLbQhhg7hnBBvc6XqQkkO0ApTZSH4RpqtEdMqwU1hqQmLQmWa4ALBU7G7We24EPVYlelK95kK3ThoJw8W1OZq8hc2YZdoAt6GQzgwPy8pIAr59CooYYLhVas8Snp6IlKOKbO8aYaA1wzo1Ska0yxsBfCcrVZbuxhwleGk7YEjoZd4u7zpGpPRFxZJeWy1rXuzZw9qiPfEcsXGt88w85dnySJ2MJlD54G228mhoIe9yl0EKU57j1TTdL7jv73mOJ/pcT3GKqHmJoLAskdwY3McSEf1Yx0TNZ+jJrxkkL62ab+gCydqvhipb99fNWPPZgmWMVn5XYbQWChzpvYEXG9W7n9xfxCoN1xpYX306U8ZazmmRb5++HrnTt45ChDvbK1dNMZUoeLZL4L9IaCr3wdCDfDAHU=
  app: api-reviewer
  on:
    repo: murilocamargos/reviewer-api
  run: python manage.py migrate