version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      # Make DB data persistent on the host
      - "./docker/db/pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: '123456A!'